
[[constraint]]
  name = "github.com/gobuffalo/buffalo"
  version = "0.12.2"

[[constraint]]
  name = "github.com/keighl/postmark"
  version = "1.1.2"

[prune]
  go-tests = true
  unused-packages = true
